language: php
php:
  - '7.3'
  - '7.4'
  - '8.0'
env:
  - DB=sqlite
install:
  - composer install
before_script:
  - echo 'Europe/Berlin' | sudo tee /etc/timezone
  - sudo dpkg-reconfigure --frontend noninteractive tzdata
script:
  - composer test
