language: php
php:
  - '7.3'
  - '7.4'
  - '8.0'
install:
  - composer install
script:
  - composer test
  - ./vendor/bin/doctrine-migrations execute --up 'GroupLife\Migrations\Version20210913213508'
